FROM ubuntu:18.04

ARG steam_username=username
ARG steam_password="password"

RUN apt update && apt install lib32gcc1 curl libsdl2-dev vim bash-completion -y
RUN mkdir -p /var/steam
RUN curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - -C /var/steam/
RUN /var/steam/steamcmd.sh +login ${steam_username} ${steam_password} +force_install_dir /var/hlds +app_update 90 validate +quit
RUN mkdir -p ~/.steam && ln -s /var/hlds ~/.steam/sdk32
RUN rm -rf /var/hlds/libSDL2.so && ln -s /usr/lib/x86_64-linux-gnu/libSDL2.so /var/hlds/
RUN echo "10" > /var/hlds/steam_appid.txt

WORKDIR "/var/hlds/"
CMD ["./hlds_run", "-game valve", "+maxplayers 16", "+map crossfire", "+exec server.cfg", "+ip 0.0.0.0", "+port 27015"]
